version: '3.7'
services: 
  web:
    container_name: nginx
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html:ro
      #- ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "6000:80"
    environment:
    - NGINX_PORT=6000
