version: '3.7'
services: 
  web:
    container_name: nginx_game
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html:ro
      #- ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "3001:80"
    environment:
    - NGINX_PORT=3001
